lin3s_admin:
    entities:
        pages:
            class: App\Domain\Model\Page\Page
            name:
                singular: admin.page.name.singular
                plural: admin.page.name.plural
            actions:
                new:
                    type: new_translatable
                    options:
                        name: admin.page.action.new
                        form: App\Infrastructure\Symfony\Form\Type\Page\AddPageType
                        confirm:
                            button: cms_kernel_admin_bridge.new.confirm.button
                            title: cms_kernel_admin_bridge.new.confirm.title
                            content:
                                main: cms_kernel_admin_bridge.new.confirm.content
                                locales:
                                    es_ES: cms_kernel_admin_bridge.locale.es_ES
                                    en_US: cms_kernel_admin_bridge.locale.en_US
                                    eu_ES: cms_kernel_admin_bridge.locale.eu_ES
                edit:
                    type: ddd_handle_command
                    options:
                        name: admin.page.action.edit
                        form: App\Infrastructure\Symfony\Form\Type\Page\EditPageType
                translate:
                    type: translate
                    options:
                        form: App\Infrastructure\Symfony\Form\Type\Page\EditPageTranslationType
                removeTranslation:
                    type: remove_translation
            list:
                fields:
                    id:
                        name: Id
                        type: string
                        options:
                            field: id
                    title:
                        name: admin.page.list.fields.title
                        type: translatable_string
                        options:
                            field: translations.title.title
                    actions:
                        name: lin3s_admin.list.table.actions
                        type: actions
                        options:
                            actions: ['edit']
                            name: lin3s_admin.list.table.actions
                    translations:
                        type: translate
                        options:
                            action: 'translate'
                filters:
                    id:
                        name: Id
                        type: text
                        field: id
                    title:
                        name: admin.page.list.filters.title
                        type: text
                        field: translations.title.title
                global_actions: ['new']

        menus:
            class: LIN3S\CMSKernel\Domain\Model\Menu\Menu
            name:
                singular: Menú
                plural: Menús
            actions:
                new:
                    type: new_translatable
                    options:
                        name: admin.menu.action.new
                        form: App\Infrastructure\Symfony\Form\Type\Menu\AddMenuType
                        confirm:
                            button: cms_kernel_admin_bridge.new.confirm.button
                            title: cms_kernel_admin_bridge.new.confirm.title
                            content:
                                main: cms_kernel_admin_bridge.new.confirm.content
                                locales:
                                    es_ES: cms_kernel_admin_bridge.locale.es_ES
                                    en_US: cms_kernel_admin_bridge.locale.en_US
                                    eu_ES: cms_kernel_admin_bridge.locale.eu_ES
                edit:
                    type: ddd_handle_command
                    options:
                        name: admin.menu.action.edit
                        form: App\Infrastructure\Symfony\Form\Type\Menu\EditMenuType
                translate:
                    type: translate
                    options:
                        form: App\Infrastructure\Symfony\Form\Type\Menu\EditMenuTranslationType
                removeTranslation:
                    type: remove_translation
            list:
                fields:
                    id:
                        name: Id
                        type: string
                        options:
                            field: id
                    name:
                        name: admin.menu.list.fields.name
                        type: translatable_string
                        options:
                            field: translations.name.name
                    actions:
                        name: lin3s_admin.list.table.actions
                        type: actions
                        options:
                            actions: ['edit']
                            name: lin3s_admin.list.table.actions
                    translations:
                        type: translate
                        options:
                            action: 'translate'
                filters:
                    id:
                        name: Id
                        type: text
                        field: id
                    name:
                        name: admin.menu.list.filters.name
                        type: text
                        field: translations.name.name
                global_actions: ['new']

lin3s_cms_kernel:
    templates:
        class_map:
            page:
                - App\Domain\Model\Page\Template\DefaultTemplate
                - App\Domain\Model\Page\Template\ContactTemplate

cms_kernel_admin_bridge:
    locales:
        default: '%locale%'
        others:
            - es_ES
            - eu_ES
