# This file is part of the Php DDD Standard project.
#
# Copyright (c) 2017 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Beñat Espiña <benatespina@gmail.com>
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

ben_gor_user:
    resource: "@BenGorUserBundle/Resources/config/routing/all.yml"

ben_gor_file:
    resource: "@BenGorFileBundle/Resources/config/routing/all.yml"

cms_kernel_admin_bridge:
    resource: "@CmsKernelAdminBridgeBundle/Resources/config/routing_locale.yml"
    prefix: "admin/"

cms_kernel_bengor_file_bridge:
    resource: "@CmsKernelBenGorFileBridgeBundle/Resources/config/routing.yml"
    prefix: "admin/"

lin3s_admin:
    resource: "@Lin3sAdminBundle/Resources/config/routing.yml"
    prefix: "admin/"

app:
    resource: "routing_app.yml"
